"""init complete schema

Revision ID: 44fb976e778d
Revises: 
Create Date: 2026-04-01 15:51:33.034257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44fb976e778d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('motions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('motion_text', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('POLITICS', 'TECHNOLOGY', 'ECONOMICS', 'PHILOSOPHY', 'CUSTOM', name='motioncategory'), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('skill_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='skilllevel'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('case_preps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('motion_id', sa.UUID(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('model_definition', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('counter_arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['motion_id'], ['motions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('debate_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('motion_id', sa.UUID(), nullable=False),
    sa.Column('case_prep_id', sa.UUID(), nullable=True),
    sa.Column('format', sa.Enum('BRITISH_PARLIAMENTARY', 'ASIAN_PARLIAMENTARY', name='matchformat'), nullable=False),
    sa.Column('human_role', sa.String(), nullable=False),
    sa.Column('skill_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='skilllevel'), nullable=False),
    sa.Column('status', sa.Enum('STARTED', 'FINISHED', 'ABORTED', name='matchstatus'), nullable=True),
    sa.Column('poi_enabled', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_prep_id'], ['case_preps.id'], ),
    sa.ForeignKeyConstraint(['motion_id'], ['motions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adjudication_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('winning_team', sa.String(), nullable=False),
    sa.Column('gov_total_score', sa.Float(), nullable=False),
    sa.Column('opp_total_score', sa.Float(), nullable=False),
    sa.Column('clash_table', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('speaker_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['debate_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('turns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('speaker_role', sa.String(), nullable=False),
    sa.Column('speaker_type', sa.Enum('HUMAN', 'AI', name='speakertype'), nullable=False),
    sa.Column('transcript_text', sa.Text(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('stt_confidence_avg', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['debate_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_performance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('speaker_role', sa.String(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('argument_score', sa.Float(), nullable=False),
    sa.Column('rebuttal_score', sa.Float(), nullable=False),
    sa.Column('structure_score', sa.Float(), nullable=False),
    sa.Column('delivery_score', sa.Float(), nullable=False),
    sa.Column('poi_score', sa.Float(), nullable=False),
    sa.Column('written_feedback', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['debate_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pois',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('turn_id', sa.UUID(), nullable=False),
    sa.Column('offered_by', sa.Enum('HUMAN', 'AI', name='speakertype'), nullable=False),
    sa.Column('poi_text', sa.Text(), nullable=False),
    sa.Column('outcome', sa.Enum('ACCEPTED', 'DECLINED', name='poioutcome'), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('offered_at_second', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['debate_sessions.id'], ),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pois')
    op.drop_table('user_performance')
    op.drop_table('turns')
    op.drop_table('adjudication_results')
    op.drop_table('debate_sessions')
    op.drop_table('case_preps')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('motions')
    # ### end Alembic commands ###
