"""Add metadata fields to ArgumentEmbedding model

Revision ID: aec73399851e
Revises: 0966735ff365
Create Date: 2026-04-20 00:34:01.714768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aec73399851e'
down_revision: Union[str, None] = '0966735ff365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first to handle existing data
    op.add_column('argument_embeddings', sa.Column('match_id', sa.UUID(), nullable=True))
    op.add_column('argument_embeddings', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('argument_embeddings', sa.Column('side', sa.String(), nullable=True))
    op.add_column('argument_embeddings', sa.Column('role', sa.String(), nullable=True))
    op.add_column('argument_embeddings', sa.Column('motion_category', sa.String(), nullable=True))
    
    # Create indexes
    op.create_index(op.f('ix_argument_embeddings_match_id'), 'argument_embeddings', ['match_id'], unique=False)
    op.create_index(op.f('ix_argument_embeddings_side'), 'argument_embeddings', ['side'], unique=False)
    op.create_index(op.f('ix_argument_embeddings_user_id'), 'argument_embeddings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('unique_case_prep', 'case_preps', type_='unique')
    op.drop_index(op.f('ix_argument_embeddings_user_id'), table_name='argument_embeddings')
    op.drop_index(op.f('ix_argument_embeddings_side'), table_name='argument_embeddings')
    op.drop_index(op.f('ix_argument_embeddings_match_id'), table_name='argument_embeddings')
    op.drop_column('argument_embeddings', 'motion_category')
    op.drop_column('argument_embeddings', 'role')
    op.drop_column('argument_embeddings', 'side')
    op.drop_column('argument_embeddings', 'user_id')
    op.drop_column('argument_embeddings', 'match_id')
    # ### end Alembic commands ###
