"""init complete schema

Revision ID: ebcc6cfe159b
Revises: 44fb976e778d
Create Date: 2026-04-01 20:55:41.711033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'ebcc6cfe159b'
down_revision: Union[str, None] = '44fb976e778d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Enable pgvector extension
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('argument_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_prep_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('embedding', Vector(1536), nullable=False),
    sa.Column('argument_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_prep_id'], ['case_preps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('argument_embeddings')
    # ### end Alembic commands ###
